/**
 * Local small-icon registry shared by IcIcon.
 *
 * DSH filenames point at SVGs copied from the local deepseek-harness checkout.
 * Lucide nodes are bundled locally and provide morphicons-compatible fallbacks
 * for semantics that DSH does not publish.
 */
import {
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  Ban,
  BookOpen,
  Brain,
  Bug,
  Calendar,
  CalendarDays,
  Check,
  ChevronDown,
  ChevronRight,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleX,
  ClipboardPaste,
  Clock3,
  CloudUpload,
  Code2,
  Columns3,
  Copy,
  Database,
  Download,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FilePenLine,
  FilePlus2,
  FileText,
  Filter,
  Folder,
  FolderOpen,
  FolderPlus,
  GitBranch,
  Grid2X2,
  Heading,
  History,
  Home,
  Image,
  ImagePlus,
  Info,
  Languages,
  Layers3,
  LayoutDashboard,
  Link,
  List,
  ListChecks,
  LoaderCircle,
  Maximize2,
  MessageSquarePlus,
  MessageSquareText,
  MessagesSquare,
  Minimize2,
  Minus,
  Network,
  PanelLeft,
  Pause,
  Pencil,
  Play,
  Plus,
  RefreshCw,
  RotateCcw,
  Rows3,
  Save,
  Scan,
  Scissors,
  Search,
  SearchCheck,
  Send,
  Server,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Square,
  Star,
  Table2,
  Tag,
  ThumbsDown,
  ThumbsUp,
  Trash2,
  TriangleAlert,
  Type as TextType,
  UnfoldVertical,
  Upload,
  Users,
  Wrench,
  X,
  type IconNode,
} from 'lucide'

/** Downloaded protocol marks and feature SVGs; provenance is recorded beside the assets. */
export const FEATURE_ICON_FILES: Record<string, string> = {
  skills: 'skills.svg',
  mcp: 'mcp.svg',
  ocr: 'ocr.svg',
  llm: 'llm.svg',
  memory: 'memory.svg',
  'floating-window': 'floating-window.svg',
  scanner: 'scanner.svg',
  appearance: 'appearance.svg',
  terminal: 'terminal.svg',
}

/** Exact semantic matches available in the DSH icon source. */
export const DSH_ICON_FILES: Record<string, string> = {
  search: 'search-outline16.svg',
  refresh: 'refresh-outline16.svg',
  'new-folder': 'project-add-outline16.svg',
  back: 'chevron-left-outline14.svg',
  'arrow-left': 'chevron-left-outline14.svg',
  check: 'check-outline16.svg',
  close: 'close-outline16.svg',
  'arrow-up': 'chevron-up-outline14.svg',
  'arrow-down': 'chevron-down-outline14.svg',
  'folder-open': 'folder-open-outline16.svg',
  git: 'branch-outline16.svg',
  todo: 'checklist-outline14.svg',
  ingest: 'data-outline16.svg',
  'arrow-right': 'chevron-right-outline14.svg',
  'multi-select': 'checklist-outline14.svg',
  trash: 'trash-outline16.svg',
  folder: 'folder-close16.svg',
  code: 'code-outline16.svg',
  'auto-awesome': 'enhance-outline16.svg',
  settings: 'settings-outline16.svg',
  'chevron-right': 'chevron-right-outline14.svg',
  'chevron-down': 'chevron-down-outline14.svg',
  add: 'plus-outline16.svg',
  replay: 'refresh-outline16.svg',
  warning: 'warning-outline16.svg',
  link: 'link-outline16.svg',
  cancel: 'close-fill14.svg',
  language: 'globe-outline14.svg',
  psychology: 'think-outline16.svg',
  spinner: 'loading-outline16.svg',
  tune: 'personalization-outline16.svg',
  play: 'play-outline16.svg',
  pause: 'pause-outline16.svg',
  'error-outline': 'warning-outline16.svg',
  'check-circle': 'check-outline16.svg',
  download: 'download-outline16.svg',
  edit: 'edit-outline16.svg',
  'view-column': 'panel-left-outline16.svg',
  'add-comment': 'new-chat-outline16.svg',
  'open-in-full': 'fullscreen-outline16.svg',
  copy: 'copy-outline16.svg',
  'thumb-up': 'like-outline16.svg',
  'thumb-down': 'dislike-outline16.svg',
  'open-in-new': 'right-up-outline16.svg',
  'more-horiz': 'ellipsis-outline16.svg',
  'view-sidebar': 'panel-left-outline16.svg',
  stop: 'stop-fill16.svg',
  send: 'send-outline16.svg',
  'fact-check': 'checklist-outline14.svg',
  archive: 'archive-outline20.svg',
  'edit-note': 'list-pen-outline16.svg',
  checklist: 'checklist-outline14.svg',
}

/** Complete morphicons-compatible coverage for every IcIcon semantic name. */
export const MORPH_ICONS: Record<string, IconNode> = {
  home: Home,
  search: Search,
  filter: Filter,
  sort: ArrowUpDown,
  unfold: UnfoldVertical,
  star: Star,
  refresh: RefreshCw,
  history: History,
  'new-folder': FolderPlus,
  'new-file': FilePlus2,
  back: ArrowLeft,
  'arrow-left': ArrowLeft,
  check: Check,
  close: X,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'folder-open': FolderOpen,
  git: GitBranch,
  todo: ListChecks,
  graph: Network,
  ingest: Database,
  'arrow-right': ArrowRight,
  'multi-select': ListChecks,
  trash: Trash2,
  document: FileText,
  folder: Folder,
  book: BookOpen,
  code: Code2,
  'auto-awesome': Sparkles,
  dashboard: LayoutDashboard,
  feedback: MessageSquareText,
  bug: Bug,
  settings: Settings,
  dns: Server,
  upload: Upload,
  'cloud-upload': CloudUpload,
  'chevron-right': ChevronRight,
  'chevron-down': ChevronDown,
  'unfold-less': Minimize2,
  add: Plus,
  replay: RotateCcw,
  warning: TriangleAlert,
  image: Image,
  link: Link,
  cancel: CircleX,
  'add-photo': ImagePlus,
  language: Languages,
  save: Save,
  label: Tag,
  'view-stream': Rows3,
  'grid-view': Grid2X2,
  event: CalendarDays,
  info: Info,
  psychology: Brain,
  'radio-unchecked': Circle,
  spinner: LoaderCircle,
  layers: Layers3,
  'view-list': List,
  tune: SlidersHorizontal,
  'center-focus': Scan,
  play: Play,
  pause: Pause,
  'text-fields': TextType,
  block: Ban,
  'error-outline': CircleAlert,
  'check-circle': CircleCheck,
  download: Download,
  edit: Pencil,
  visibility: Eye,
  'visibility-off': EyeOff,
  'view-column': Columns3,
  group: Users,
  'add-comment': MessageSquarePlus,
  forum: MessagesSquare,
  'open-in-full': Maximize2,
  schedule: Clock3,
  copy: Copy,
  'thumb-up': ThumbsUp,
  'thumb-down': ThumbsDown,
  'open-in-new': ExternalLink,
  'more-horiz': Ellipsis,
  'view-sidebar': PanelLeft,
  shield: ShieldCheck,
  stop: Square,
  send: Send,
  build: Wrench,
  'fact-check': ListChecks,
  file: File,
  archive: Archive,
  'edit-note': FilePenLine,
  'table-chart': Table2,
  title: Heading,
  'manage-search': SearchCheck,
  hub: Network,
  checklist: ListChecks,
  calendar: Calendar,
  cut: Scissors,
  paste: ClipboardPaste,
  remove: Minus,
}

/** Safe fallback used only when an extension supplies an unknown semantic name. */
export const FALLBACK_MORPH_ICON = Wrench

/**
 * Creates a static SVG from the same local icon data consumed by morphicons.
 * Use only for DOM-enhancement code that cannot mount a Vue component.
 */
export function createStaticMorphIcon(name: string, size: number): SVGSVGElement {
  const namespace = 'http://www.w3.org/2000/svg'
  const svg = document.createElementNS(namespace, 'svg')
  svg.setAttribute('width', String(size))
  svg.setAttribute('height', String(size))
  svg.setAttribute('viewBox', '0 0 24 24')
  svg.setAttribute('fill', 'none')
  svg.setAttribute('stroke', 'currentColor')
  svg.setAttribute('stroke-width', '1.8')
  svg.setAttribute('stroke-linecap', 'round')
  svg.setAttribute('stroke-linejoin', 'round')
  svg.setAttribute('aria-hidden', 'true')
  svg.setAttribute('data-icon-source', 'morphicons')
  svg.setAttribute('data-icon-name', name)

  for (const [tag, attributes] of MORPH_ICONS[name] ?? FALLBACK_MORPH_ICON) {
    const child = document.createElementNS(namespace, tag)
    for (const [attribute, value] of Object.entries(attributes)) {
      child.setAttribute(attribute, String(value))
    }
    svg.appendChild(child)
  }
  return svg
}
