/*
 * API route registry for the editor front-end.
 *
 * Usage:
 * Import these constants from API clients and stores instead of hard-coding
 * endpoint strings inside components.
 */

export const API_ROUTES = {
  SETTINGS_PROFILE: '/settings/profile',
  SETTINGS_KNOWLEDGE_DIR: '/settings/profile/knowledge-dir',
  SETTINGS_FONT_CONFIG: '/settings/appearance/font',
  SETTINGS_APPEARANCE_CONFIG: '/settings/appearance/config',
  SETTINGS_EDITOR_PASTE_CONFIG: '/settings/editor/paste',
  SETTINGS_KNOWLEDGE_INGESTION: '/settings/profile/ingestion',
  SETTINGS_SYSTEM_PROMPT: '/settings/memory/system-prompts',
  SETTINGS_SYSTEM_PROMPT_ENTRIES: '/settings/memory/system-prompts',
  SETTINGS_MEMORIES: '/settings/memory/memories',
  SETTINGS_MEMORY_CONFIG: '/settings/memory/config',
  KNOWLEDGE_REBUILD: '/knowledge/rebuild',
  KNOWLEDGE_REBUILD_STREAM: '/knowledge/rebuild/stream',
  KNOWLEDGE_FILES: '/knowledge/files',
  KNOWLEDGE_FILE_CREATE: '/knowledge/files/file',
  KNOWLEDGE_FILE_CONTENT: '/knowledge/files/content',
  KNOWLEDGE_FILE_PREVIEW: '/knowledge/files/preview',
  KNOWLEDGE_FILE_PDF_PAGE: '/knowledge/files/pdf-page',
  KNOWLEDGE_FILE_UPLOAD: '/knowledge/files/upload',
  KNOWLEDGE_FILE_INGEST: '/knowledge/files/ingest',
  KNOWLEDGE_FILE_INGEST_STREAM: '/knowledge/files/ingest/stream',
  KNOWLEDGE_FILE_INGEST_PATH: '/knowledge/files/ingest-path',
  KNOWLEDGE_FILE_INGEST_PATH_STREAM: '/knowledge/files/ingest-path/stream',
  KNOWLEDGE_INGESTION_JOBS: '/knowledge/ingestion/jobs',
  KNOWLEDGE_FILE_FOLDER: '/knowledge/files/folder',
  KNOWLEDGE_FILE_COPY: '/knowledge/files/copy',
  KNOWLEDGE_FILE_RENAME: '/knowledge/files/rename',
  KNOWLEDGE_FILE_TRASH: '/knowledge/files/trash',
  KNOWLEDGE_FILE_EVENTS: '/knowledge/files/events',
  KNOWLEDGE_INDEX_RUN: '/knowledge/index/run',
  KNOWLEDGE_INDEX_STATUS: '/knowledge/index/status',
  AGENT_STREAM: '/agent/stream',
  AGENT_STREAM_RUN: '/agent/stream-run',
  AGENT_ATTACHMENTS_UPLOAD: '/agent/attachments/upload',
  AGENT_ATTACHMENTS: '/agent/attachments',
  AGENT_ATTACHMENT_RAW: '/agent/attachments/raw',
  AGENT_CURRENT_DOCUMENT_CONTEXT: '/agent/editor-context/current-document',
  AGENT_TOOLS: '/agent/tools',
  AGENT_EVENTS: '/agent/events',
  AGENT_RECALL_DETAILS: '/agent/recall-details',
  AGENT_TASK_SUGGESTIONS: '/agent/task-suggestions',
  AGENT_TOKEN_USAGE: '/agent/token-usage',
  ACTIVITY_HEATMAP: '/activity/heatmap',
  AGENT_CHILDREN: '/agent/children',
  AGENT_CHILD_WAKEUP_CLAIM: (runId: string) => `/agent/children/${encodeURIComponent(runId)}/claim-wakeup`,
  AGENT_CHILD_DSH_WEB: (runId: string) => `/agent/children/${encodeURIComponent(runId)}/dsh-web`,
  SESSION_MESSAGE_HISTORY: '/sessions/observability/history',
  DEBUG_RUNTIME_APIS: '/debug/runtime-apis',
  DEBUG_GLOBAL_CONSTANTS: '/debug/global-constants',
  DEBUG_MULTIMODAL_INGESTION: '/debug/multimodal-ingestion',
  KNOWLEDGE_SEARCH: '/knowledge/search',
  UNIFIED_SEARCH: '/search',
  KNOWLEDGE_GRAPH: '/knowledge/graph',
  KNOWLEDGE_GRAPH_NODES: '/knowledge/graph/nodes',
  KNOWLEDGE_GRAPH_REBUILD: '/knowledge/graph/rebuild',
  KNOWLEDGE_GRAPH_REBUILD_CANCEL: '/knowledge/graph/rebuild/cancel',
  KNOWLEDGE_GRAPH_REBUILD_STATUS: '/knowledge/graph/rebuild/status',
  KNOWLEDGE_GRAPH_DEDUP: '/knowledge/graph/dedup',
  KNOWLEDGE_GRAPH_DEDUP_STATUS: '/knowledge/graph/dedup/status',
  GIT_STATUS: '/git/status',
  GIT_INIT: '/git/init',
  GIT_DIFF: '/git/diff',
  GIT_HISTORY: '/git/history',
  GIT_RESTORE: '/git/restore',
  GIT_COMMIT: '/git/commit',
  GIT_PUSH: '/git/push',
  GIT_BRANCHES: '/git/branches',
  GIT_REMOTES: '/git/remotes',
  GIT_SWITCH: '/git/switch',
  GIT_PULL: '/git/pull',
  LIBRARY_ITEMS: '/library/items',
  LIBRARY_ITEM_BOOK: '/library/items/book',
  LIBRARY_ITEM_COLLECTION: '/library/items/collection',
  LIBRARY_TAGS: '/library/tags',
  LIBRARY_COVER_UPLOAD: '/library/assets/cover',
  COMPONENT_LIBRARY_ITEMS: '/component-library/components',
  VAULT_STATUS: '/vault/status',
  VAULT_DEBUG_MASTER_PASSWORD: '/vault/debug/master-password',
  VAULT_SETUP: '/vault/setup',
  VAULT_UNLOCK: '/vault/unlock',
  VAULT_RESET_PASSWORD: '/vault/reset-password',
  VAULT_LOCK: '/vault/lock',
  VAULT_ITEMS: '/vault/items',
  VAULT_ITEM_PURGE: '/vault/items/purge',
  VAULT_ITEM_TRASH: '/vault/items/trash',
  VAULT_ITEM_RESTORE: '/vault/items/restore',
  VAULT_TAGS: '/vault/tags',
  VAULT_EXPORT: '/vault/export',
  VAULT_IMPORT: '/vault/import',
  VAULT_ASSETS: '/vault/assets',
  FAVORITES: '/favorites',
  SCANNER: '/scanner',
  SCANNER_FILES: '/scanner/files',
  SCANNER_URLS: '/scanner/urls',
  PRIVACY: '/privacy',
  FEEDBACK: '/feedback',
  SMART_FORMS_LIST: '/smart-forms/list',
  SMART_FORMS_SAVE: '/smart-forms/save',
  SMART_FORM_DETAIL: (formId: string) => `/smart-forms/${encodeURIComponent(formId)}`,
  LITERATURE_READING_ENTRIES: '/literature-reading/entries',
  LITERATURE_READING_ROW: (formId: string, rowId: string) => `/literature-reading/${encodeURIComponent(formId)}/rows/${encodeURIComponent(rowId)}`,
  LITERATURE_READING_VIEW: (formId: string, rowId: string) => `/literature-reading/${encodeURIComponent(formId)}/rows/${encodeURIComponent(rowId)}/view`,
  LITERATURE_READING_DUPLICATE: (formId: string, rowId: string) => `/literature-reading/${encodeURIComponent(formId)}/rows/${encodeURIComponent(rowId)}/duplicate`,
  STRUCTURED_GENERATION_FIELDS: '/structured-generation/fields',
  SETTINGS_MODEL_CONFIG: '/settings/llm/config',
  SETTINGS_MODEL_CONFIG_SAVED: '/settings/llm/config/saved',
  SETTINGS_VLM_CONFIG: '/settings/vlm/config',
  SETTINGS_VLM_CONFIG_SAVED: '/settings/vlm/config/saved',
  SETTINGS_VLM_CHECK: '/settings/vlm/check',
  SETTINGS_VLM_LOCAL_OCR_ENSURE: '/settings/vlm/local-ocr/ensure',
  SETTINGS_WEB_SEARCH: '/settings/web-search/config',
  SETTINGS_FLOATING_CONFIG: '/settings/floating/config',
  SETTINGS_DISABLED_TOOLS: '/settings/tools/disabled',
  SETTINGS_AVAILABLE_TOOLS: '/settings/tools/available',
  SETTINGS_TERMINAL_SANDBOX: '/settings/terminal/sandbox',
  SETTINGS_GRAPH_CONFIG: '/settings/graph/config',
  SETTINGS_SAFETY_SENSITIVE_WORDS: '/settings/safety/sensitive-words',
  SETTINGS_MODEL_STATUS: '/settings/models/status',
  SETTINGS_MODEL_DOWNLOAD: '/settings/models/download',
  SETTINGS_MODEL_LOAD: '/settings/models/load',
  SETTINGS_MODEL_CHECK: '/settings/models/check',
  SETTINGS_MODEL_DOWNLOAD_PROGRESS: '/settings/models/download-progress',
  SETTINGS_MODEL_MANAGEMENT: '/settings/models/management',
  SETTINGS_MODEL_PREFERENCES: '/settings/models/preferences',
  SETTINGS_MODEL_INITIALIZE: '/settings/models/initialize',
  SETTINGS_MODEL_DOWNLOAD_CONFIRMED: '/settings/models/download-confirmed',
  SETTINGS_MODEL_DELETE: '/settings/models/delete',
  SETTINGS_STORAGE_CONFIG: '/settings/storage/config',
  SETTINGS_STORAGE_CLEAR: '/settings/storage/clear',
  SETTINGS_DSH_SDK_MANAGEMENT: '/settings/sdks/dsh/management',
  SETTINGS_DSH_SDK_INITIALIZE: '/settings/sdks/dsh/initialize',
  SETTINGS_DSH_SDK_INSTALL: '/settings/sdks/dsh/install',
  SETTINGS_DSH_SDK_INSTALL_CANCEL: '/settings/sdks/dsh/install/cancel',
  SETTINGS_DSH_SDK_REPAIR: '/settings/sdks/dsh/repair',
  SETTINGS_DSH_SDK_UNINSTALL: '/settings/sdks/dsh/uninstall',
  SETTINGS_LATEX_STATUS: '/settings/latex/status',
  SETTINGS_LATEX_MANAGEMENT: '/settings/latex/management',
  SETTINGS_LATEX_INSTALL: '/settings/latex/install',
  SETTINGS_LATEX_INSTALL_CANCEL: '/settings/latex/install/cancel',
  SETTINGS_LATEX_UNINSTALL: '/settings/latex/uninstall',
  KNOWLEDGE_LATEX_COMPILE: '/knowledge/latex/compile',
  SKILLS: '/skills',
  SKILLS_SPEC: '/skills/spec',
  SKILL_ENABLED: (skillId: string) => `/skills/${encodeURIComponent(skillId)}/enabled`,
  TODO_LIST: '/todo/list',
  TODO_ADD: '/todo/add',
  TODO_TOGGLE: '/todo/toggle',
  TODO_EDIT: '/todo/edit',
  TODO_DELETE: '/todo/delete',
  AUTOMATION_LIST: '/automation/list',
  AUTOMATION_ADD: '/automation/add',
  AUTOMATION_TOGGLE: '/automation/toggle',
  AUTOMATION_RUNS: '/automation/runs',
  AUTOMATION_DELETE: '/automation/delete',
  AGENT_QUEUE_TASKS: '/agent-queue/tasks',
  AGENT_QUEUE_SETTINGS: '/agent-queue/settings',
  AGENT_QUEUE_TRANSITION: (taskId: string) => `/agent-queue/tasks/${encodeURIComponent(taskId)}/transition`,
  AGENT_QUEUE_TASK: (taskId: string) => `/agent-queue/tasks/${encodeURIComponent(taskId)}`,
  AGENT_QUEUE_CONTINUE: (taskId: string) => `/agent-queue/tasks/${encodeURIComponent(taskId)}/continue`,
  SESSION_TASK_LIST: (sessionId: string) => `/sessions/${sessionId}/task-list`,
  SESSION_TASK_LIST_COMPLETE_ITEM: (sessionId: string) => `/sessions/${sessionId}/task-list/complete-item`,
  SESSION_TASK_LIST_FINISH: (sessionId: string) => `/sessions/${sessionId}/task-list/finish`,
  SESSION_STATE: (sessionId: string) => `/sessions/${encodeURIComponent(sessionId)}/state`,
  SESSION_CHANGES: (sessionId: string) => `/sessions/${encodeURIComponent(sessionId)}/changes`,
  SESSION_CHANGE_UNDO: (sessionId: string, snapshotId: string) => (
    `/sessions/${encodeURIComponent(sessionId)}/changes/${encodeURIComponent(snapshotId)}/undo`
  ),
} as const
