/**
 * Shared fallback display names for the current native ToolRegistry.
 * Backend trace.display_name remains authoritative, including MCP tools.
 * tests/test_tool_catalog_presentation.py checks this catalog when tools change.
 */
export const TOOL_DISPLAY_NAMES: Readonly<Record<string, string>> = {
  "add_automation": "创建自动化任务",
  "add_favorite": "新增收藏",
  "add_library_book": "新增图书",
  "add_library_collection": "新增集锦",
  "add_todo": "新增待办",
  "cancel_knowledge_job": "取消知识任务",
  "complete_task_list_item": "完成任务项",
  "continue_child_agent": "继续 DSH 子 Agent",
  "create_component": "新增组件",
  "create_custom_skill": "定制 Skill",
  "create_knowledge_folder": "创建文件夹",
  "create_smart_form": "创建智能表格",
  "create_task_list": "创建任务列表",
  "create_user_feedback": "新增用户反馈",
  "delete_component": "删除组件",
  "delete_custom_skill": "删除定制 Skill",
  "delete_file_graph": "删除文件图谱",
  "delete_knowledge_file": "删除文件",
  "delete_long_term_memory": "删除记忆",
  "delete_long_term_rule": "删除长期规则",
  "delete_todo": "删除待办",
  "delete_user_feedback": "删除用户反馈",
  "download_file": "下载文件",
  "edit_todo": "编辑待办",
  "export_smart_form": "导出智能表格",
  "extract_all_file_graphs": "全量图谱抽取",
  "extract_selected_file_graphs": "多选文件图谱抽取",
  "fill_smart_form_cells": "填充智能表项",
  "find_knowledge_graph_paths": "查找图谱关系路径",
  "finish_task_list": "完成任务列表",
  "get_component": "读取组件",
  "get_current_viewing_document": "获取当前文档",
  "get_custom_skill": "读取定制 Skill",
  "get_knowledge_context": "检索知识",
  "get_knowledge_file_status": "查询文件管线状态",
  "get_knowledge_job_status": "查询知识任务",
  "get_knowledge_url": "获取知识URL",
  "get_library_item": "读取图书馆条目",
  "get_long_term_memory": "检索记忆",
  "get_selected_knowledge_files": "获取多选文件",
  "get_smart_form": "获取智能表格",
  "get_smart_form_literature": "获取表项文献",
  "get_smart_form_schema": "获取表格结构",
  "get_task_list_status": "获取任务列表状态",
  "get_user_feedback": "读取用户反馈",
  "git_add_remote": "新增 Git 远程",
  "git_commit_files": "Git 提交",
  "git_create_branch": "创建 Git 分支",
  "git_diff": "Git 差异",
  "git_history": "Git 历史",
  "git_init_repository": "初始化 Git",
  "git_pull_branch": "Git 拉取",
  "git_push_branch": "Git 推送",
  "git_restore_files": "Git 回滚",
  "git_status": "Git 状态",
  "git_switch_branch": "切换 Git 分支",
  "import_smart_form": "导入智能表格",
  "ingest_all_knowledge_files": "全量灌库",
  "ingest_selected_knowledge_files": "多选文件灌库",
  "list_available_tools": "查看可用工具",
  "list_components": "筛选组件",
  "list_favorites": "列出收藏",
  "list_knowledge_files": "列出文件",
  "list_knowledge_trash": "列出最近删除",
  "list_library_items": "列出图书馆",
  "list_library_tags": "列出图书馆标签",
  "list_skills": "列出技能",
  "list_smart_forms": "列出智能表格",
  "list_todos": "列出待办",
  "list_user_feedback": "列出用户反馈",
  "patch_knowledge_file": "局部修改文件",
  "patch_smart_form_rows": "编辑智能表项",
  "permanently_delete_knowledge_trash": "彻底删除知识文件",
  "preview_smart_form_fill": "预览智能填充",
  "read_file": "阅读文件",
  "read_tool_result": "继续读取工具结果",
  "remove_favorite": "取消收藏",
  "remove_library_item": "移出图书馆",
  "rename_knowledge_file": "重命名文件",
  "request_user_input": "询问用户",
  "restore_knowledge_file": "恢复知识文件",
  "retry_failed_graph_extraction": "重试图谱失败文件",
  "retry_failed_knowledge_files": "重试灌库失败文件",
  "run_terminal_command": "终端命令",
  "save_uploaded_attachment_to_knowledge": "附件存入知识库",
  "search_knowledge": "四库联合搜索",
  "search_knowledge_graph_nodes": "搜索语义图谱节点",
  "set_skill_enabled": "切换 Skill",
  "show_markdown_html": "展示Markdown-HTML",
  "spawn_child_agent": "召唤子 Agent",
  "test_custom_skill": "测试定制 Skill",
  "toggle_todo": "切换待办状态",
  "understand_image": "识图",
  "update_component": "修改组件",
  "update_custom_skill": "更新定制 Skill",
  "update_library_item": "更新图书馆条目",
  "update_smart_form": "更新智能表格",
  "update_user_feedback": "修改用户反馈",
  "use_skill": "使用技能",
  "validate_component": "验证组件",
  "validate_custom_skill": "验证定制 Skill",
  "wait_for_child_agents": "等待子 Agent",
  "web_image_search": "联网搜索图片",
  "web_search": "联网搜索",
  "write_knowledge_file": "创作文件",
  "write_long_term_memory": "写入记忆",
  "write_long_term_rule": "写入长期规则"
}
