/** Real MCP UI regressions for shared sidebar arrows, animated disclosures, todo checkboxes and button consistency. */
import { expect, test } from '@playwright/test'
import path from 'node:path'

test('MCP controls reuse sidebar motion and consistent action styles', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('用户 ID', { exact: true }).fill(`mcp-style-${Date.now()}`)
  await page.getByRole('button', { name: '进入', exact: true }).click()
  await expect(page.locator('#editor-user-id')).toBeHidden()
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await page.getByRole('button', { name: 'MCP', exact: true }).click()
  await page.getByRole('button', { name: '添加服务', exact: true }).click()
  const section = page.locator('.mcp-settings-section')
  await expect(section.locator('details')).toHaveCount(0)
  const advanced = page.getByRole('button', { name: '高级设置', exact: true })
  const panel = section.locator('.mcp-advanced .settings-disclosure-panel')
  await panel.evaluate(element => {
    element.addEventListener('transitionrun', event => {
      if ((event as TransitionEvent).propertyName === 'height') element.setAttribute('data-height-transitions', String(Number(element.getAttribute('data-height-transitions') || 0) + 1))
    })
  })
  await expect(advanced.locator('.disclosure-chevron')).toHaveCount(1)
  await advanced.click()
  await expect(advanced).toHaveAttribute('aria-expanded', 'true')
  await expect(page.locator('#mcp-timeout')).toBeVisible()
  await expect(panel).toHaveAttribute('data-height-transitions', '1')
  await expect.poll(() => panel.evaluate(e => e.getBoundingClientRect().height)).toBeGreaterThan(40)
  await advanced.click()
  await expect(advanced).toHaveAttribute('aria-expanded', 'false')
  await expect(page.locator('#mcp-timeout')).toBeHidden()
  await expect(panel).toHaveAttribute('data-height-transitions', '2')
  const cancel = section.getByRole('button', { name: '取消', exact: true }).first()
  expect(await cancel.evaluate(e => e.getBoundingClientRect().width)).toBeGreaterThanOrEqual(88)
  for (const button of await section.locator('.mcp-toolbar button.mcp-text-button').all()) {
    await expect(button.locator('.ic-icon')).toHaveCount(1)
    expect(await button.evaluate(e => getComputedStyle(e).borderTopWidth)).toBe('0px')
  }
  for (const button of await section.locator('.mcp-bottom-actions > button').all()) {
    const style = await button.evaluate(e => ({ border: getComputedStyle(e).borderTopWidth, fill: getComputedStyle(e).backgroundColor }))
    expect(style.border).toBe('1px')
    expect(style.fill).toBe('rgba(0, 0, 0, 0)')
  }
  await page.getByRole('tab', { name: '服务器', exact: true }).click()
  const server = page.getByRole('region', { name: 'MCP 服务器', exact: true })
  await expect(server.locator('.creative-checkbox')).not.toHaveCount(0)
  await expect(server.locator('.creative-checkbox .check-path').first()).toHaveAttribute('d', 'M14,23 L19,28 L30,15')
  expect(await server.locator('.mcp-tool-row').first().evaluate(e => getComputedStyle(e).borderBottomWidth)).toBe('0px')
  const reset = server.getByRole('button', { name: '取消修改', exact: true })
  expect(await reset.evaluate(e => e.getBoundingClientRect().width)).toBeGreaterThanOrEqual(100)
  await page.getByRole('button', { name: '外观', exact: true }).click()
  await page.getByRole('button', { name: '浅色', exact: true }).click()
  await page.getByRole('button', { name: 'MCP', exact: true }).click()
  await page.getByRole('tab', { name: '客户端', exact: true }).click()
  await advanced.click()
  await expect(panel).toBeVisible()
  await expect.poll(() => panel.evaluate(e => (e as HTMLElement).style.height)).toBe('')
  await page.locator('.settings-body').evaluate(e => { e.scrollTop = 0 })
  await page.evaluate(() => window.scrollTo({ left: 0, top: 0 }))
  await page.screenshot({ path: path.resolve('../docs/acceptance/mcp/client-light.png') })
  await page.getByRole('tab', { name: '服务器', exact: true }).click()
  await expect.poll(() => section.locator(':scope > .form-height-transition').evaluate(e => (e as HTMLElement).style.height)).toBe('auto')
  await page.locator('.settings-body').evaluate(e => { e.scrollTop = 0 })
  await page.evaluate(() => window.scrollTo({ left: 0, top: 0 }))
  await page.screenshot({ path: path.resolve('../docs/acceptance/mcp/server-light.png') })
})
