/** Actual MCP settings smoke: real database, stdio/HTTP SDK, credentials, import and responsive screenshots. */
import { expect, test } from '@playwright/test'
import path from 'node:path'
import fs from 'node:fs/promises'

test('MCP client/server management is operational through Vite', async ({ page, request }) => {
  const owner = `mcp-ui-${Date.now()}`
  const root = path.resolve('..')
  const screenshots = path.join(root, 'docs/acceptance/mcp')
  await fs.mkdir(screenshots, { recursive: true })
  const errors: string[] = []
  page.on('pageerror', error => errors.push(String(error)))
  await page.goto('/')
  await page.getByLabel('用户 ID', { exact: true }).fill(owner)
  await page.getByRole('button', { name: '进入', exact: true }).click()
  await expect(page.locator('#editor-user-id')).toBeHidden()
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await page.getByRole('button', { name: 'MCP', exact: true }).click()
  await page.locator('#mcp-client-enabled').check()
  await page.getByRole('button', { name: '添加服务', exact: true }).click()
  await page.locator('#mcp-name').fill('stdio 实际联通')
  await page.locator('#mcp-command').fill('D:/Softwares/Python/Python312/python.exe')
  await page.getByRole('button', { name: '添加参数', exact: true }).click()
  await page.getByLabel('参数 1', { exact: true }).fill(path.join(root, 'tests/mcp_stdio_fixture.py'))
  await page.getByRole('button', { name: '测试连接', exact: true }).click()
  await expect(page.getByText('连接通过，发现 2 个工具', { exact: true })).toBeVisible({ timeout: 15_000 })
  await page.locator('#mcp-name').fill('stdio 已编辑')
  await expect(page.getByText('配置已改变，之前的测试结果不再适用。')).toBeVisible()
  await page.getByRole('button', { name: '保存并应用', exact: true }).first().click()
  await expect(page.getByText('已保存并生效；下一轮 Agent 使用新配置')).toBeVisible({ timeout: 15_000 })
  await page.evaluate(() => window.scrollTo({ left: 0, top: 0 }))
  await page.screenshot({ path: path.join(screenshots, 'client-desktop.png') })
  await page.getByRole('tab', { name: '服务器', exact: true }).click()
  await page.locator('#mcp-server-enabled').check()
  await page.locator('#mcp-listen-port').fill('8781')
  await page.getByRole('button', { name: '选择只读工具', exact: true }).click()
  await page.getByRole('button', { name: '保存并应用', exact: true }).last().click()
  await expect(page.getByText('配置已保存，服务器正在运行')).toBeVisible({ timeout: 15_000 })
  await page.getByRole('button', { name: '创建凭据', exact: true }).click()
  await page.locator('#mcp-credential-name').fill('外部阅读客户端')
  await page.getByRole('button', { name: '创建', exact: true }).click()
  const token = await page.getByLabel('新访问令牌', { exact: true }).inputValue()
  expect(token).toMatch(/^mw_mcp_/)
  await page.getByRole('button', { name: '验证初始化与只读调用', exact: true }).click()
  await expect(page.getByText('初始化、工具发现和只读调用通过')).toBeVisible({ timeout: 15_000 })
  await page.getByRole('button', { name: '已保存，关闭', exact: true }).click()
  await page.locator('.settings-body').evaluate(e => { e.scrollTop = 0 })
  await page.evaluate(() => window.scrollTo({ left: 0, top: 0 }))
  await page.screenshot({ path: path.join(screenshots, 'server-desktop.png') })
  await page.getByRole('tab', { name: '客户端', exact: true }).click()
  await page.getByRole('button', { name: '添加服务', exact: true }).click()
  await page.locator('#mcp-name').fill('HTTP 实际联通')
  await page.locator('#mcp-transport').selectOption('http')
  await page.locator('#mcp-url').fill('http://127.0.0.1:8781/mcp')
  await page.getByRole('button', { name: '添加请求头', exact: true }).click()
  await page.getByLabel('请求头名称 1', { exact: true }).fill('Authorization')
  await page.getByLabel('请求头值 1', { exact: true }).fill(`Bearer ${token}`)
  await page.getByRole('button', { name: '测试连接', exact: true }).click()
  await expect(page.getByText(/连接通过，发现 \d+ 个工具/)).toBeVisible({ timeout: 15_000 })
  await page.getByRole('button', { name: '保存并应用', exact: true }).first().click()
  await expect(page.getByText('已保存并生效；下一轮 Agent 使用新配置')).toBeVisible({ timeout: 15_000 })
  await expect(page.getByLabel('请求头值 1', { exact: true })).toHaveValue('')
  await page.getByRole('button', { name: '导入配置', exact: true }).click()
  await page.locator('#mcp-import-json').fill(JSON.stringify({ connections: [
    { name: 'stdio 已编辑', command: 'D:/Softwares/Python/Python312/python.exe', args: [path.join(root, 'tests/mcp_stdio_fixture.py')] },
    { name: '导入配置', command: 'D:/Softwares/Python/Python312/python.exe', args: [path.join(root, 'tests/mcp_stdio_fixture.py')] },
  ] }))
  await page.getByRole('button', { name: '检查配置', exact: true }).click()
  await expect(page.getByText('名称已存在', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '确认导入', exact: true }).click()
  await expect(page.getByText('导入完成', { exact: true })).toBeVisible({ timeout: 15_000 })
  await page.reload()
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await page.getByRole('button', { name: 'MCP', exact: true }).click()
  await expect(page.locator('.mcp-connection-row')).toHaveCount(3)
  // Real drafts survive switching between client and server; navigation cancellation preserves them.
  await page.getByRole('button', { name: '添加服务', exact: true }).click()
  await page.locator('#mcp-name').fill('未保存草稿')
  await page.getByRole('tab', { name: '服务器', exact: true }).click()
  await page.getByRole('tab', { name: '客户端', exact: true }).click()
  await expect(page.locator('#mcp-name')).toHaveValue('未保存草稿')
  page.once('dialog', dialog => dialog.dismiss())
  await page.getByRole('button', { name: '基础设置', exact: true }).click()
  await expect(page.locator('#mcp-name')).toBeVisible()
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '取消', exact: true }).first().click()
  for (const width of [768, 480, 360]) {
    await page.setViewportSize({ width, height: 900 })
    await page.locator('.settings-body').evaluate(e => { e.scrollTop = 0 })
    await page.evaluate(() => window.scrollTo({ left: 0, top: 0 }))
  await page.screenshot({ path: path.join(screenshots, `client-${width}.png`) })
    const overflow = await page.locator('.mcp-settings-section').evaluate(e => e.scrollWidth > e.clientWidth + 1)
    expect(overflow).toBe(false)
    await page.getByRole('tab', { name: '服务器', exact: true }).click()
    await page.locator('.settings-body').evaluate(e => { e.scrollTop = 0 })
    await page.evaluate(() => window.scrollTo({ left: 0, top: 0 }))
  await page.screenshot({ path: path.join(screenshots, `server-${width}.png`) })
    expect(await page.locator('.mcp-settings-section').evaluate(e => e.scrollWidth > e.clientWidth + 1)).toBe(false)
    await page.getByRole('tab', { name: '客户端', exact: true }).click()
  }
  expect(errors).toEqual([])
  // Stop both client connections and the server through their real APIs after UI verification.
  expect((await request.put(`/settings/mcp/client?user_id=${owner}`, { data: { enabled: false } })).ok()).toBe(true)
  const status = await (await request.get(`/settings/mcp/server?user_id=${owner}`)).json()
  expect((await request.put(`/settings/mcp/server?user_id=${owner}`, { data: { ...status.config, enabled: false } })).ok()).toBe(true)
})
